Update NUnit to 4.x (and `LangVersion` to 14) (#6802)
* Update NUnit to 4.x

I left this alone in https://github.com/ppy/osu-framework/pull/6788
because it was going to be painful (cf.
https://github.com/ppy/osu/pull/36996/changes/73561f809deffa508d909f84a14c5916d64e7ab6),
but as it turns out, being able to update to C# 14 (which is made
possible by .NET 10) makes the upgrade *much* less painful, as upstream
added a passthrough leveraging extension methods on static classes that
makes it possible to just not update most usages
(https://github.com/nunit/nunit/pull/5054).

Note that there's another reason to bump `LangVersion` here; without
bumping it to at least 13 you run into compiler errors related to
overload resolution ambiguity around the deprecated `TestDelegate`
(see https://docs.nunit.org/articles/nunit/release-notes/framework.html#the-following-issues-are-marked-as-breaking-changes-1).

* Remove unused usings

Bumping the `LangVersion` seems to have unlocked *something* that allows
`.Contains()` to be used on arrays without a LINQ using.

* Suppress suggestion to use "field backed properties"

Bumping C# language version to 14 surfaces a bunch of inspections like

```
Error: /home/runner/work/osu-framework/osu-framework/osu.Framework/Allocation/TimedExpiryCache.cs(97,13): error IDE0032: Use auto property (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0032) [/home/runner/work/osu-framework/osu-framework/osu.Framework/osu.Framework.csproj]
```

The change that the compiler here attempts to enforce is:

```diff
diff --git a/osu.Framework/Allocation/TimedExpiryCache.cs b/osu.Framework/Allocation/TimedExpiryCache.cs
index f851524ecf..d25ce17662 100644
--- a/osu.Framework/Allocation/TimedExpiryCache.cs
+++ b/osu.Framework/Allocation/TimedExpiryCache.cs
@@ -94,20 +94,18 @@ private class TimedObject<T>
         {
             public DateTimeOffset LastAccessTime;

-            private readonly T value;
-
             public T Value
             {
                 get
                 {
                     updateAccessTime();
-                    return value;
+                    return field;
                 }
             }

             public TimedObject(T value)
             {
-                this.value = value;
+                Value = value;
                 updateAccessTime();
             }

```

What this is, is a new C# 14 language feature called ["field backed
properties"](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/field).
The gist of it appears to be that you apparently are no longer required
to declare a backing field yourself, and instead you can use a new
`field` keyword to refer to the automatically-generated backing field.
Assignments to the backing field - if any - are replaced with
assignments to the property which... has no getter.

To me this is quite abhorrent. Unfortunately there is no `.editorconfig`
switch targeted at this specific new dingle, or at least I can't find
one. You have to completely shut down the auto-property enforcement on
that level. ReSharper will still enforce that, but the C# compiler
itself will not.

Chuck another C# language release in the "half of new features is neat,
half is horrible abominations" bin I guess.

* Update InspectCode to 2026.2.1

Judging by how many errors the previous version spews, I'm pretty sure
it's fundamentally incompatible with C# 14.